### ISSUE TITLE
[FEATURE] Add folder to upload temporary files

### ISSUE THREAD

**Issue by idylicaro** [idylicaro/go-server-files#4]
#### Description
Add folder to upload temporary files and add .gitignore in this files

#### Images
Non

#### Tasks
Subtasks that are contained in this actual issue 
- [x] Put pattern folder in upload endpoint
- [x] Add .gitignore to ignore "folder"/**
- [ ] Make the test coverage of UploadFile controller

**Comment by idylicaro** [comment]
This is way to mock functions more easy...

I usually does something like these,

```golang
var getHostname = os.Hostname

and in test file,

getHostname = func() {
return "something", nil // or a variable
}
```

BY: { "github":"[github.com/shuLhan](http://github.com/shuLhan)", "site":"[kilabit.info](http://kilabit.info/)" }
