### ISSUE TITLE
[FEATURE] Improve architecture

### ISSUE THREAD

**Issue by idylicaro** [idylicaro/go-server-files#6]
#### Description
Define architecture with best practices in Golang gin API.

#### Tasks
Subtasks that are contained in this actual issue:
- [ ] Diagram of architecture
- [ ] Refactor code to apply architecture
- [ ] Explain folders and your responsibilities
